FROM laravel/sail-8.4-app

# Instalar dependências e extensões como root
USER root
RUN apt-get update && apt-get install -y \
    libgd-dev \
    && docker-php-ext-install gd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Voltar para o usuário sail
USER sail